export const data = [
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
];