export const data = [
    {
        name:'num1',
        id:1,
        content:'1111',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'2222',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'222',
        rating:4,
    },
    {
        name:'num1',
        id:1,
        content:'ddddddddddddddddddddddddd',
        rating:4,
    },
];